var questionInfo = [
 { id:  1,   clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  2,   clues: [{slideid: 3, vid: 1}],
	answer: {slideid: 4}},
 { id:  3,   clues: [{slideid: 5}],
	answer: {slideid: 6}},
 { id:  4,   clues: [{slideid: 7}],
	answer: {slideid: 8}},
 { id:  5,   clues: [{slideid: 9}],
	answer: {slideid: 10}},
 { id:  6,   clues: [{slideid: 11}],
	answer: {slideid: 12}},
 { id:  7,   clues: [{slideid: 13}],
	answer: {slideid: 14}},
 { id:  8,   clues: [{slideid: 15}], 
	answer: {slideid: 16}},
 { id:  9,   clues: [{slideid: 17}],
	answer: {slideid: 18}},
 { id: 10,   clues: [{slideid: 19}],
	answer: {slideid: 20}},
 { id: 11,   clues: [{slideid: 21, vid: 2}],
	answer: {slideid: 22}},
 { id: 12,   clues: [{slideid: 23}],
	answer: {slideid: 24}},
 { id: 13,   clues: [{slideid: 25}],
	answer: {slideid: 26}},
 { id: 14,   clues: [{slideid: 27}, {slideid: 28}],
	answer: {slideid: 29}},
 { id: 15,   clues: [{slideid: 30}],
	answer: {slideid: 31}},
 { id: 16,   clues: [{slideid: 32}, {slideid: 33}, {slideid: 34}],
	answer: {slideid: 35}},
 { id: 17,   clues: [{slideid: 36}, {slideid: 37}, {slideid: 38}],
	answer: {slideid: 39}},
 { id: 18,   clues: [{slideid: 40}],
	answer: {slideid: 41}},
 { id: 19,   clues: [{slideid: 42}],
	answer: {slideid: 43}},
 { id: 20,   clues: [{slideid: 44}],
	answer: {slideid: 45}},
 { id: 21,   clues: [{slideid: 46}],
	answer: {slideid: 47}},
 { id: 22,   clues: [{slideid: 48}],
	answer: {slideid: 49}},
 { id: 23,   clues: [{slideid: 50}],
	answer: {slideid: 51}},
 { id: 24,   clues: [{slideid: 52}],
	answer: {slideid: 53}},
 { id: 25,   clues: [{slideid: 54}],
	answer: {slideid: 55}},
 { id: 26,   clues: [{slideid: 56}],
	answer: {slideid: 57}},
 { id: 27,   clues: [{slideid: 58}],
	answer: {slideid: 59}},
 { id: 28,   clues: [{slideid: 60}, {slideid: 61}, {slideid: 62}, {slideid: 63}, {slideid: 64}],
	answer: {slideid: 65}},
 { id: 29,   clues: [{slideid: 66}, {slideid: 67}, {slideid: 68}, {slideid: 69}],
	answer: {slideid: 70}},
 { id: 30,   clues: [{slideid: 71}, {slideid: 72}, {slideid: 73}, {slideid: 74}, {slideid: 75}],
	answer: {slideid: 76}},
 { id: 31,   clues: [{slideid: 77}, {slideid: 78}, {slideid: 79}, {slideid: 80}, {slideid: 81}, {slideid: 82}, {slideid: 83}, {slideid: 84}],
	answer: {slideid: 85}},
 { id: 32,   clues: [{slideid: 86}, {slideid: 87}, {slideid: 88}, {slideid: 89, vid: 3}],
	answer: {slideid: 90}},
 { id: 33,   clues: [{slideid: 91}, {slideid: 92}, {slideid: 93}, {slideid: 94}],
	answer: {slideid: 95}},
];

var linkInfo = [
	"Liberty City",
	"East Coast",
	"Etymology",
	"Italians",
	"France",
	"Femme Fatale",
	"Cricket",
	"Cricket",
	"Brit Lit",
	"Sea Sickness",
	"Oceania",
	"Calendar",
	"Nippon",
	"\u00B5"
];

var r2topics = [
	{name: "(AP) Staged", qids: [16, 17]},
	{name: "Lesbians", qids: [18, 19]},
	{name: "Bollysylvania", qids: [20, 21]},
	{name: "Food for thought", qids: [22, 23]},
	{name: "Somebody call 911", qids: [24, 25]},
	{name: "City bank", qids: [26, 27]},
];

var r3keys = [
	{name: "Dollars Colony", kqid: 28},
	{name: "Stormy ya Sunny?", msg: "PG13QuizOnlyWholeSomeQuestionsCheeThooShaantamPaapamException"},
	{name: "Fwd: Fwd: Re: Fwd:", msg: "PleaseDontLynchTheQuizMasterException"},
	{name: "Bonjour, mi amore", kqid: 29},
	{name: "Winds of Winter", msg: "OhYouSweetSummerChildException"},
	{name: "Dee and Dum", kqid: 30},
	{name: "Bard but not Beedle", kqid: 31},
	{name: "Tabs vs Spaces", msg: "TabsAreAHeresySpacesAreTheOneTrueGodException"},
	{name: "Hum log-o", kqid: 32},
	{name: "Kal Aaj aur Kal", kqid: 33},
];