var questionInfo = [
 { id:  1, location: [90, 90, 30], genre: "Carnatic", clues: [{slideid: 1}, {slideid: 2}, {slideid: 3}],
	answer: {slideid: 4}},
 { id:  2, location: [90, 80, 30], genre: "Hindustani", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  3, location: [60, 70, 30], genre: "African", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  4, location: [70, 80, 30], genre: "Ghazal", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  5, location: [60, 50, 30], genre: "Algerian", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  6, location: [90, 30, 30], genre: "Thai Pop", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  7, location: [80, 60, 30], genre: "Bolly\nwood 1", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  8, location: [80, 50, 30], genre: "Bolly\nwood 2", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id:  9, location: [80, 40, 30], genre: "Indipop\n1", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 10, location: [80, 30, 30], genre: "Indipop\n2", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 11, location: [90, 20, 30], genre: "K Pop", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 12, location: [10, 60, 30], genre: "50s\nPop", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 13, location: [20, 70, 30], genre: "Jazz", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 14, location: [20, 60, 30], genre: "Soul", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 15, location: [30, 90, 35], genre: "Western\nClassical", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 16, location: [20, 80, 35], genre: "Classical\nReferences(AP)", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 17, location: [10, 50, 35], genre: "Local\nVariables(AP)", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 18, location: [30, 40, 35], genre: "UnVidia\n(AP)", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 19, location: [40, 60, 35], genre: "TV Tunes\n(AP)", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 20, location: [30, 20, 35], genre: "N || K\n(AP)", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 21, location: [30, 60, 35], genre: "In Living\nCover (AP)", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 22, location: [10, 30, 30], genre: "Heavy\nMetal", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 23, location: [10, 20, 30], genre: "Death\nMetal", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 24, location: [20, 30, 30], genre: "90's R & B", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 25, location: [20, 20, 30], genre: "00's R & B", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 26, location: [30, 50, 30], genre: "70's Disco", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 27, location: [20, 50, 30], genre: "80's Disco", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 28, location: [40, 40, 30], genre: "Synth", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 29, location: [20, 10, 30], genre: "Neo Soul", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 30, location: [30, 30, 30], genre: "80's Pop", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 31, location: [30, 10, 30], genre: "90's Pop", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 32, location: [20, 40, 30], genre: "Rock", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 33, location: [10, 10, 30], genre: "Emo", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 34, location: [40, 50, 30], genre: "Reggae", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 35, location: [50, 60, 30], genre: "Country", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 36, location: [40, 20, 30], genre: "Hip Hop", clues: [{slideid: 1}],
	answer: {slideid: 2}},
 { id: 37, location: [40, 30, 30], genre: "Folk", clues: [{slideid: 1}],
	answer: {slideid: 2}},
];